### ISSUE TITLE
pip install keybase-api needs root privs

### ISSUE THREAD

**Issue by dametenshi** [ianchesal/keybase-python#2]
To install the requirements, ```pip install keybase-api``` as outlined in the readme.md doesn't work. Simply doing ```sudo pip install keybase-api``` is sufficient.

**Comment by ianchesal** [comment]
Are you not running a personal python or hombrew'ed python? I have deep aversions to mucking with system pythons and their installed eggs. I'm okay changing the README.md to add the `sudo` for system pythons.

For dev work I *highly* recommend a virtualenv python and not running `make setup` against system python.

**Comment by dametenshi** [comment]
According to ```brew leaves``` I haven't installed anything custom. Should be plain ol' system python:

```bash
$ python --version
Python 2.7.6

$ which python
/usr/bin/python
```

**Comment by ianchesal** [comment]
Yea, system python is owned by someone other than you so you'll always have to `sudo` to install additional libraries. Best not to mess with system python.

See the updated https://github.com/ianchesal/keybase-python/blob/develop/README.md

I added `[sudo]` to the install instructions and I added a section under Development for using VirtualEnv to do your dev work. Highly recommend VirtualEnv.
