### ISSUE TITLE
Command line client

### ISSUE THREAD

**Issue by vext01** [ianchesal/keybase-python#3]
Hey,

Just found this project whilst looking for an alternative to the node.js implementation. It's a real pain.

I was wondering if you are planning on including a command line client to keybase. This would be most useful.

Thanks.

**Comment by ianchesal** [comment]
I hadn't planned on a command line interface. What about the official node.js CLI is causing you pain?

**Comment by vext01** [comment]
Indeed. It's annoying to install and update, and node stuff really doesn't sit well with my OS package manager (OpenBSD). Building packages of Python stuff, on the other hand, is easy.

Would you be oppose if I/we/whoever were to begin work on a command line client in a branch?

Thanks

**Comment by ianchesal** [comment]
> Would you be oppose if I/we/whoever were to begin work on a command line client in a branch?

Definitely not! :+1: 

Feel free to issue PRs if you want to keep it all in one place and not fork the package on pypi.

For me, personally, I have a bias against using this software to access your keyring where you store your private key. And to keeping your private key on the keybase servers. See [this blog post](http://mostlywrong.net/on-the-future-of-the-keybase-python-api/). But that's me. What others do is what others do and I wouldn't get in the way of that.

**Comment by vext01** [comment]
I'm not big on the idea of uploading keys. Agreed.

If I were to make a CLI, I would probably have it shell out to gpg.

**Comment by ianchesal** [comment]
The gnupg library for Python from isislovecruft will shell out to gnupg. But you'd need to import your private key to make it work if you want to be able to decrypt things sent to you. That's the second area where I'm not comfortable -- I'd rather not have this library messing with the private keys at all.
